POST https://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "firstname": "Ebimobowei",
    "email": "ebi4jah1555a@gmail.com",
    "password": "qwerty"
    
}


###
POST https://homify-nine.vercel.app/api/auth/signup
Content-Type: application/json

{
    "agreeToTerms": true,
    "confirmPassword": "qwerty",
    "firstname": "Ebimobowei",
    "lastname": "Pondei",
    "phone": "8105910313",
    "email": "ebi4jah1555@gmail.com",
    "password": "qwerty"
    
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ebi4jah15@gmail.com",
    "password": "qwerty"
}


###
POST https://homify-nine.vercel.app/api/auth/login
Content-Type: application/json

{
    "email": "ebi4jah1555@gmail.com",
    "password": "qwerty"
    
}


###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ebi4jah15@gmail.com",
    "password": "qwerty"
}

