import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import logo from '../public/images/logo.png'
import menuItem from '../data/db'
import { Button } from "@/components/ui/button";
import { ChevronDown } from "lucide-react";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="bg-blue-3000 shadow-sm">
          <div className="container mx-auto px-6 md:px-16 py-3 md:py-5 flex items-center justify-between">
            <div className="flex items-center justify-between gap-8 w-full">
              <div>
                <Image src="/logo.svg" alt="Homely Buy Logo" width={40} height={40} />
              </div>
              <nav className="hidden md:flex items-center space-x-6">
                <a href="#" className="text-blue-600 font-medium">
                  Buy
                </a>
                <a href="#" className="text-gray-600 hover:text-blue-600">
                  Rent
                </a>
                <a href="#" className="text-gray-600 hover:text-blue-600">
                  Short Rent
                </a>
                <a href="#" className="text-gray-600 hover:text-blue-600">
                  About
                </a>
                <a href="#" className="text-gray-600 hover:text-blue-600">
                  Agents
                </a>
              </nav>
              <div>
                <Button className="bg-blue-500 hover:bg-blue-600 rounded-full">
                  PAUL SLACK <ChevronDown className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
